In [1]:
import numpy as np

In [3]:
list1 = [1, 2, 3, 4, 5]
list1

[1, 2, 3, 4, 5]

In [5]:
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5])

In [7]:
list1 + list1

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
arr1+arr1

array([ 2,  4,  6,  8, 10])

In [11]:
list2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(list2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 3)


In [17]:
print(arr1.size)
print(arr2.size)

5
6


In [19]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.random.randint(2, 11, size = (2, 3))

array([[ 9,  6,  5],
       [ 3,  7, 10]])

In [53]:
np.arange(1, 51, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [55]:
arr3 = np.arange(1, 51, 1)
arr3.reshape(5, 10)
arr3.reshape(10, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [57]:
arr3.dtype

dtype('int32')

In [59]:
arr3.astype('float32')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.],
      dtype=float32)

In [61]:
arr2 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [63]:
arr2[0]

array([1, 2, 3])

In [65]:
arr2[0][1]

2

In [67]:
arr2[0, 1]

2

In [77]:
arr4 = np.arange(1, 51, 1).reshape(5, 10)
arr4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [79]:
arr4[1][5:8]

array([16, 17, 18])

In [81]:
arr4[:, 0]

array([ 1, 11, 21, 31, 41])

In [83]:
arr4[3, :]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [85]:
arr4[:, 0:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

In [89]:
data = np.genfromtxt('data/ratings.txt', delimiter = '::', dtype = 'int')
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [91]:
data.shape

(1000209, 4)

In [93]:
data[:, 2]

array([5, 3, 3, ..., 5, 4, 4])

In [95]:
data[:, 2].mean()

3.581564453029317

In [97]:
data[data[:, 0] == 1][:, 2].mean()

4.188679245283019

In [99]:
user_id = data[:, 0]
user_id_uni = np.unique(user_id)
user_id_uni
len(user_id_uni)

6040